Weather/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forecast.urls')),
    path('', include('core.urls')),
    path('', include('news.urls')),
]

core/urls.py
from django.urls import path
from .views import video, contact, photos

app_name = 'core'
urlpatterns = [
    path('contact/', contact, name='contact'),
    path('video/<int:page_num>/', video, name='video'),
    path('photos/<int:page_num>/', photos, name='photos'),
]

forecast/urls.py
from django.urls import path
from .views import index

app_name = 'forecast'
urlpatterns = [
    path('', index, name='index'),
]

news/urls.py
from django.urls import path
from .views import news, single

app_name = 'news'
urlpatterns = [
    path('news/<str:name>/<int:page_num>/', news, name='news'),
    path('single/<str:name>/', single, name='single'),
]

news/models.py
from django.db import models

# Create your models here.

news/views.py
import requests
from django.core.paginator import Paginator
from django.shortcuts import render
from datetime import datetime


def get_current_time(time):
    formatted_time = ''
    formatted_time += str(time.year) + "-"
    formatted_time += str(time.month) + "-"
    formatted_time += str(time.day - 1)
    return formatted_time


def news(request, name, page_num):
    global url_categories, url_countries, url_hot_news, url_news

    articles_news = []

    # -------------------------- hot_news -------------------------------
    url_hot_news = ('https://newsapi.org/v2/everything?'
                    'qInTitle=+weather forecast&'
                    'from={}&'.format(get_current_time(datetime.today())) +
                    'sortBy=popularity&'
                    'apiKey=21f9eff5ef8e4fa9b470994ce83c2688')

    request_hot_news = requests.get(url_hot_news).json()

    # print(url_hot_news)
    # print(request_hot_news)

    articles_hot_news = []
    for i in range(0, request_hot_news['totalResults'], 1):
        if (request_hot_news['articles'][i]['title'] is not None) and (
                request_hot_news['articles'][i]['description'] is not None) and (
                request_hot_news['articles'][i]['urlToImage'] is not None) and (
                request_hot_news['articles'][i]['content']):
            articles_hot_news.append({
                'title': request_hot_news['articles'][i]['title'],
            })

        if len(articles_hot_news) >= 6:
            break
    # -------------------------- news -------------------------------
    if name == 'none':
        url_news = ('https://newsapi.org/v2/everything?'
                    'qInTitle="weather forecast"&'
                    'from={}&'.format(get_current_time(datetime.today())) +
                    'sortBy=popularity&'
                    'pageSize=7&'
                    'page={}&'.format(page_num) +
                    'apiKey=21f9eff5ef8e4fa9b470994ce83c2688')

        request_news = requests.get(url_news).json()

        # print(url_news)
        # print(request_news)

        for i in range(0, request_news['totalResults'], 1):
            if (request_news['articles'][i]['title'] is not None) and (
                    request_news['articles'][i]['description'] is not None) and (
                    request_news['articles'][i]['urlToImage'] is not None) and (
                    request_news['articles'][i]['content']):
                articles_news.append({
                    'title': request_news['articles'][i]['title'],
                    'description': request_news['articles'][i]['description'],
                    'urlToImage': request_news['articles'][i]['urlToImage'],
                })

            if len(articles_news) >= 5:
                break
    else:
        # -------------------------- categories -------------------------------
        if len(name) > 2:
            url_categories = ('https://newsapi.org/v2/top-headlines?'
                              'category={}&'.format(name) +
                              'pageSize=7&'
                              'page={}&'.format(page_num) +
                              'apiKey=21f9eff5ef8e4fa9b470994ce83c2688')

            request_categories = requests.get(url_categories).json()

            # print(url_categories)
            # print(request_categories)

            for i in range(0, request_categories['totalResults'], 1):
                if (request_categories['articles'][i]['title'] is not None) and (
                        request_categories['articles'][i]['description'] is not None) and (
                        request_categories['articles'][i]['urlToImage'] is not None) and (
                        request_categories['articles'][i]['content']):
                    articles_news.append({
                        'title': request_categories['articles'][i]['title'],
                        'description': request_categories['articles'][i]['description'],
                        'urlToImage': request_categories['articles'][i]['urlToImage'],
                    })

                if len(articles_news) >= 5:
                    break
        # -------------------------- countries -------------------------------
        else:
            url_countries = ('https://newsapi.org/v2/top-headlines?'
                             'country={}&'.format(name) +
                             'pageSize=7&'
                             'page={}&'.format(page_num) +
                             'apiKey=21f9eff5ef8e4fa9b470994ce83c2688')

            request_countries = requests.get(url_countries).json()

            # print(url_countries)
            # print(request_countries)

            for i in range(0, request_countries['totalResults'], 1):
                if (request_countries['articles'][i]['title'] is not None) and (
                        request_countries['articles'][i]['description'] is not None) and (
                        request_countries['articles'][i]['urlToImage'] is not None) and (
                        request_countries['articles'][i]['content']):
                    articles_news.append({
                        'title': request_countries['articles'][i]['title'],
                        'description': request_countries['articles'][i]['description'],
                        'urlToImage': request_countries['articles'][i]['urlToImage'],
                    })

                if len(articles_news) >= 5:
                    break

    # -------------------------- pagination -------------------------------
    # print(len(articles_news))
    paginator = Paginator(articles_news, 1)
    page_number = page_num
    page_obj = paginator.get_page(page_number)
    # print(page_obj)

    # print(page_obj.has_previous())
    # print(page_obj.previous_page_number())

    # print(page_obj.has_next())
    # print(page_obj.next_page_number())

    context = {
        'articles_news': articles_news,
        'articles_hot_news': articles_hot_news,
        'page_obj': page_obj,
        'name': name,
    }

    return render(request, 'news/news.html', context)


def single(request, name):
    # print(request)
    # print(name)
    # -------------------------- hot_news -------------------------------
    articles_hot_news = []
    url_hot_news = ('https://newsapi.org/v2/everything?'
                    'qInTitle=+weather forecast&'
                    'from={}&'.format(get_current_time(datetime.today())) +
                    'sortBy=popularity&'
                    'apiKey=8e8831c2f33b4772a65ea8bb06cf54ff')

    request_hot_news = requests.get(url_hot_news).json()

    # print(url_hot_news)
    # print(request_hot_news)

    for i in range(0, request_hot_news['totalResults'], 1):
        if (request_hot_news['articles'][i]['title'] is not None) and (
                request_hot_news['articles'][i]['description'] is not None) and (
                request_hot_news['articles'][i]['urlToImage'] is not None) and (
                request_hot_news['articles'][i]['content']):
            articles_hot_news.append({
                'title': request_hot_news['articles'][i]['title'],
            })

        if len(articles_hot_news) >= 6:
            break

    # -------------------------- news -------------------------------
    url_news = ('https://newsapi.org/v2/everything?'
                'qInTitle=+{}&'.format(name) +
                'from={}&'.format(get_current_time(datetime.today())) +
                'apiKey=8e8831c2f33b4772a65ea8bb06cf54ff')

    request_news = requests.get(url_news).json()

    # print(url_news)
    # print(request_news)

    context = {
        'title': request_news['articles'][0]['title'],
        'description': request_news['articles'][0]['description'],
        'urlToImage': request_news['articles'][0]['urlToImage'],
        'content': request_news['articles'][0]['content'],
        'articles_hot_news': articles_hot_news,
    }
    return render(request, 'news/single.html', context)

news/templates/news/news.html
{% extends 'base.html' %}
{% load static %}
{% block title %} | News {% endblock title %}
{% block current_news %}current-menu-item{% endblock current_news %}
{% block content %}
    <!-- .main-content -->
    <main class="main-content">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url 'forecast:index' %}">Home</a>
                <span>News</span>
            </div>
        </div>

        <div class="fullwidth-block">
            <div class="container">
                <div class="row">
                    <div class="content col-md-8">
                        {% for article in articles_news %}
                            <div class="post">
                                <h2 class="entry-title">{{ article.title }}</h2>
                                <div class="featured-image"><img
                                        src="{{ article.urlToImage }}"
                                        alt=""></div>
                                <p>{{ article.description }}</p>
                                <a href="{% url 'news:single' article.title %}" class="button">Read more</a>
                            </div>
                        {% endfor articles_hot_news %}

                        <center>
                            {#                        {% if page_obj.has_other_pages %}#}
                            {% if page_obj.has_previous %}
                                <a class="btn btn-outline-info mb-4" href="{% url 'news:news' name 1 %}">First</a>
                                <a class="btn btn-outline-info mb-4"
                                   href="{% url 'news:news' name page_obj.previous_page_number %}">Previous</a>
                            {% endif %}

                            {% for num in page_obj.paginator.page_range %}
                                {% if page_obj.number == num %}
                                    <a class="btn btn-info mb-4" href="{% url 'news:news' name num %}">{{ num }}</a>
                                {% elif num > page_obj.number|add:'-3' and  num < page_obj.number|add:'3' %}
                                    <a class="btn btn-outline-info mb-4"
                                       href="{% url 'news:news' name num %}">{{ num }}</a>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <a class="btn btn-outline-info mb-4"
                                   href="{% url 'news:news' name page_obj.next_page_number %}">Next</a>
                                <a class="btn btn-outline-info mb-4"
                                   href="{% url 'news:news' name page_obj.paginator.num_pages %}">Last</a>
                            {% endif %}
                            {#                        {% endif %}#}
                        </center>
                    </div>

                    <div class="sidebar col-md-3 col-md-offset-1">
                        <div class="widget">
                            <h3 class="widget-title">Hot News</h3>
                            <ul class="arrow-list">
                                {% for article in articles_hot_news %}
                                    <li><a href="{% url 'news:single' article.title %}">{{ article.title }}</a></li>
                                {% endfor articles_hot_news %}
                            </ul>
                        </div>

                        <div class="widget">
                            <h3 class="widget-title">Categories</h3>
                            <ul class="arrow-list">
                                <li><a href="{% url 'news:news' 'business' 1 %}">business</a></li>
                                <li><a href="{% url 'news:news' 'general' 1 %}">general</a></li>
                                <li><a href="{% url 'news:news' 'health' 1 %}">health</a></li>
                                <li><a href="{% url 'news:news' 'science' 1 %}">science</a></li>
                                <li><a href="{% url 'news:news' 'technology' 1 %}">technology</a></li>
                                <li><a href="{% url 'news:news' 'sports' 1 %}">sports</a></li>
                                <li><a href="{% url 'news:news' 'entertainment' 1 %}">entertainment</a></li>
                            </ul>
                        </div>

                        <div class="widget top-rated">
                            <h3 class="widget-title">Top Countries</h3>
                            <ul>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'ar' 1 %}">Argentina</a></h3>
                                </li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'br' 1 %}">Brazil</a></h3>
                                </li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'cn' 1 %}">China</a></h3></li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'de' 1 %}">Germany</a></h3>
                                </li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'jp' 1 %}">Japan</a></h3></li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'hl' 1 %}">Netherlands</a>
                                </h3></li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'pt' 1 %}">Portugal</a></h3>
                                </li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'uk' 1 %}">United Kingdom</a>
                                </h3></li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'us' 1 %}">United States</a>
                                </h3></li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'tr' 1 %}">Turkey</a></h3>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- .main-content -->
{% endblock content %}

news/templates/news/single.html
{% extends 'base.html' %}
{% load static %}
{% block title %} | Article {% endblock title %}
{% block current_news %}current-menu-item{% endblock current_news %}
{% block content %}
    <!-- .main-content -->
    <main class="main-content">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url 'forecast:index' %}">Home</a>
                <a href="{% url 'news:news' 'none' '1' %}">News</a>
                <span>{{ title }}</span>
            </div>
        </div>


        <div class="fullwidth-block">
            <div class="container">
                <div class="row">
                    <div class="content col-md-8">
                        <div class="post single">
                            <h2 class="entry-title">{{ title }}</h2>
                            <div class="featured-image"><img
                                    src="{{ urlToImage }}" alt=""></div>

                            <div class="entry-content">
                                <p>{{ content }}</p>

                                <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed
                                    quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque
                                    porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci
                                    velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore
                                    magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum
                                    exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi
                                    consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit
                                    esse quam nihil molestiae consequatur.</p>

                                <blockquote>
                                    <p>{{ description }}</p>
                                </blockquote>

                                <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis
                                    praesentium voluptatum deleniti corrupti quos dolores et quas molestias
                                    excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui
                                    officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem
                                    rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis
                                    est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere
                                    possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus
                                    autem quibusdam et aut officiis debitis aut rerum.</p>

                                <p>Dlorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non
                                    numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat
                                    voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis
                                    suscipit beatae vitae dicta sunt explicabo e veritatis et quasi architecto
                                    beatae vitae dicta sunt explicabo earum rerum.</p>
                            </div>

                        </div>

                    </div>
                    <div class="sidebar col-md-3 col-md-offset-1">
                        <div class="widget">
                            <h3 class="widget-title">Hot News</h3>
                            <ul class="arrow-list">
                                {% for article in articles_hot_news %}
                                    <li><a href="{% url 'news:single' article.title %}">{{ article.title }}</a></li>
                                {% endfor articles_hot_news %}
                            </ul>
                        </div>

                        <div class="widget">
                            <h3 class="widget-title">Categories</h3>
                            <ul class="arrow-list">
                                <li><a href="{% url 'news:news' 'business' 1 %}">business</a></li>
                                <li><a href="{% url 'news:news' 'general' 1 %}">general</a></li>
                                <li><a href="{% url 'news:news' 'health' 1 %}">health</a></li>
                                <li><a href="{% url 'news:news' 'science' 1 %}">science</a></li>
                                <li><a href="{% url 'news:news' 'technology' 1 %}">technology</a></li>
                                <li><a href="{% url 'news:news' 'sports' 1 %}">sports</a></li>
                                <li><a href="{% url 'news:news' 'entertainment' 1 %}">entertainment</a></li>
                            </ul>
                        </div>

                        <div class="widget top-rated">
                            <h3 class="widget-title">Top Countries</h3>
                            <ul>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'ar' 1 %}">Argentina</a></h3>
                                </li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'br' 1 %}">Brazil</a></h3>
                                </li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'cn' 1 %}">China</a></h3></li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'de' 1 %}">Germany</a></h3>
                                </li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'jp' 1 %}">Japan</a></h3></li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'hl' 1 %}">Netherlands</a>
                                </h3></li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'pt' 1 %}">Portugal</a></h3>
                                </li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'uk' 1 %}">United Kingdom</a>
                                </h3></li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'us' 1 %}">United States</a>
                                </h3></li>
                                <li><h3 class="entry-title"><a href="{% url 'news:news' 'tr' 1 %}">Turkey</a></h3>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- .main-content -->
{% endblock content %}