Weather/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forecast.urls')),
    path('', include('core.urls')),
    path('', include('news.urls')),
]

core/urls.py
from django.urls import path
from .views import video, contact, photos

app_name = 'core'
urlpatterns = [
    path('contact/', contact, name='contact'),
    path('video/<int:page_num>/', video, name='video'),
    path('photos/<int:page_num>/', photos, name='photos'),
]

forecast/urls.py
from django.urls import path
from .views import index

app_name = 'forecast'
urlpatterns = [
    path('', index, name='index'),
]

news/urls.py
from django.urls import path
from .views import news, single

app_name = 'news'
urlpatterns = [
    path('news/<str:name>/<int:page_num>/', news, name='news'),
    path('single/<str:name>/', single, name='single'),
]

core/models.py
from ckeditor.fields import RichTextField
from django.db import models


class Email(models.Model):
    email_address = models.EmailField()

    def __str__(self):
        return self.email_address


class Contact(models.Model):
    your_name = models.CharField(max_length=20)
    your_email_address = models.EmailField()
    your_company_name = models.CharField(max_length=20, null=True, blank=True)
    your_website = models.URLField(null=True, blank=True)
    your_message = RichTextField(max_length=256)

    def __str__(self):
        return self.your_name

core/forms.py
from django import forms
from .models import Email, Contact


class EmailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email_address'].widget.attrs.update(
            {
                'placeholder': 'Enter your email to subscribe...',
                'type': 'text',
                'label': '',
            }
        )

    class Meta:
        model = Email
        fields = '__all__'
        widgets = {
            'email_address': forms.EmailInput(),
        }


class ContactForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['your_name'].widget.attrs.update(
            {
                'placeholder': 'Your name...',
                'type': 'text',
                'label': '',
            }
        )
        self.fields['your_email_address'].widget.attrs.update(
            {
                'placeholder': 'Email Address...',
                'type': 'text',
                'label': '',
            }
        )
        self.fields['your_company_name'].widget.attrs.update(
            {
                'placeholder': 'Company name..',
                'type': 'text',
                'label': '',
            }
        )
        self.fields['your_website'].widget.attrs.update(
            {
                'placeholder': 'Website...',
                'type': 'text',
                'label': '',
            }
        )
        self.fields['your_message'].widget.attrs.update(
            {
                'placeholder': 'Message...',
                'type': 'textarea',
                'label': '',
            }
        )

    class Meta:
        model = Contact
        fields = '__all__'
        widgets = {
            'email_address': forms.EmailInput(),
            'your_website': forms.URLInput(),
        }

core/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from pypexels import PyPexels
from .forms import EmailForm, ContactForm
from pexels_api import API


def SubscriptionEmail(request):
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            form.save()
            redirect('forecast:index')
        else:
            raise ValueError('Validation failed')

    form = EmailForm()

    return render(request, 'base.html', {'email_form': form})


def photos(request, page_num):
    # print(request)
    # print(page_num)

    PEXELS_API_KEY = '563492ad6f917000010000016c169600b01549b190ba2ed39b1d9000'
    api = API(PEXELS_API_KEY)

    api.search('landscape', page=page_num, results_per_page=5)
    photos_left = api.get_entries()

    # print(api.search('landscape', page=page_num, results_per_page=5))
    # print(api.get_entries())

    api.search('weather', page=page_num, results_per_page=5)
    photos_right = api.get_entries()

    # print(api.search('weather', page=page_num, results_per_page=5))
    # print(api.get_entries())

    photos_list_left = []
    photos_list_right = []
    for photo in photos_left:
        photos_list_left.append({
            'url': photo.medium,
            'description': photo.description,
        })
    for photo in photos_right:
        photos_list_right.append({
            'url': photo.medium,
            'description': photo.description,
        })

    # print(len(photos_list_left + photos_list_right))
    paginator = Paginator(photos_list_left + photos_list_right, 1)
    page_number = page_num
    page_obj = paginator.get_page(page_number)
    # print(page_obj)

    # print(page_obj.has_previous())
    # print(page_obj.previous_page_number())
    #
    # print(page_obj.has_next())
    # print(page_obj.next_page_number())

    context = {
        'photos_list_left': photos_list_left,
        'photos_list_right': photos_list_right,
        'page_obj': page_obj,
    }
    return render(request, 'core/photos.html', context)


def video(request, page_num):
    print(request)
    print(page_num)

    api_key = '563492ad6f917000010000016c169600b01549b190ba2ed39b1d9000'
    py_pexel = PyPexels(api_key=api_key)

    search_videos_top = py_pexel.videos_search(query="forest", page=page_num, per_page=8)
    video_list_top = []

    for video in search_videos_top.entries:
        video_list_top.append({
            'url': video.url,
            'image': video.image,
            'duration': video.duration,
            'user': video.user['name'],
        })
        print(video.url)
        print(video.image)

    search_videos_bottom = py_pexel.videos_search(query="landscape", page=page_num, per_page=8)
    video_list_bottom = []
    for video in search_videos_bottom.entries:
        video_list_bottom.append({
            'url': video.url,
            'image': video.image,
            'duration': video.duration,
            'user': video.user['name'],
        })
        print(video.url)
        print(video.image)

    print(len(video_list_bottom + video_list_top))
    paginator = Paginator(video_list_bottom + video_list_top, 1)
    page_number = page_num
    page_obj = paginator.get_page(page_number)
    print(page_obj)

    context = {
        'video_list_bottom': video_list_bottom,
        'video_list_top': video_list_top,
        'page_obj': page_obj,
    }

    return render(request, 'core/live-cameras.html', context)


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            redirect('core:contact')
        else:
            raise ValueError('Validation failed')

    form = ContactForm()
    return render(request, 'core/contact.html', {'contact_form': form})

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">

    <title>Weather PT forecast {% block title %}{% endblock title %}</title>

    <!-- Loading third party fonts -->
    <link href="http://fonts.googleapis.com/css?family=Roboto:300,400,700|" rel="stylesheet" type="text/css">
    <link href="{% static 'core/fonts/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Loading main css file -->
    <link rel="stylesheet" href="{% static 'core/style.css' %}">

    <!--[if lt IE 9]-->
    <script src="{% static 'core/js/ie-support/html5.js' %}"></script>
    <script src="{% static 'core/js/ie-support/respond.js' %}"></script>
    <!--[endif]-->

</head>
<body>
<div class="site-content">
    <!-- .site-header -->
    <div class="site-header">
        <div class="container">
            <a href="{% url 'forecast:index' %}" class="branding">
                <img src="{% static 'core/images/logo.png' %}" alt="" class="logo">
                <div class="logo-type">
                    <h1 class="site-title">PT Company</h1>
                    <small class="site-description">tagline goes here</small>
                </div>
            </a>

            <!-- Default snippet for navigation -->
            <div class="main-navigation">
                <button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
                <ul class="menu">
                    <li class="menu-item {% block current_home %}{% endblock current_home %}"><a
                            href="{% url 'forecast:index' %}">Home</a></li>
                    <li class="menu-item {% block current_news %}{% endblock current_news %}"><a
                            href="{% url 'news:news' 'none' 1 %}">News</a></li>
                    <li class="menu-item {% block current_live %}{% endblock current_live %}"><a
                            href="{% url 'core:video' 1 %}">Videos</a></li>
                    <li class="menu-item {% block current_photos %}{% endblock current_photos %}"><a
                            href="{% url 'core:photos' 1 %}">Photos</a></li>
                    <li class="menu-item {% block current_contact %}{% endblock current_contact %}"><a
                            href="{% url 'core:contact' %}">Contact</a></li>
                </ul> <!-- .menu -->
            </div> <!-- .main-navigation -->

            <div class="mobile-navigation"></div>

        </div>
    </div>
    <!-- .site-header -->

    <!-- .site-content -->
    {% block content %}
    {% endblock content %}
    <!-- .site-content -->

    <!-- .site-footer -->
    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <form action="" method="post" class="subscribe-form">
                        {% csrf_token %}
{#                        <label>#}
{#                            <input type="text" placeholder="Enter your email to subscribe...">#}
{#                        </label>#}
                        {{ email_form.email_address }}
                        <input type="submit" value="Subscribe">
                    </form>
                </div>
                <div class="col-md-3 col-md-offset-1">
                    <div class="social-links">
                        <a href="https://m.facebook.com/pooria.tavana"><i class="fa fa-facebook"></i></a>
                        <a href="https://twitter.com/Pooria9731?s=09"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-google-plus"></i></a>
                        <a href="#"><i class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>

            <center><p class="colophon">Copyright 2014. All rights reserved</p></center>
        </div>
    </footer>
    <!-- .site-footer -->
</div>

<script src="{% static 'core/js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'core/js/plugins.js' %}"></script>
<script src="{% static 'core/js/app.js' %}"></script>
{% block js %}{% endblock js %}

</body>
</html>